birth_year = input("Enter your birth year in 4 digit format: ")
age = 2021 - int(birth_year)
print("The answer is")
print(age)
print("2020 minus 2008 equals 12, so....")
print("THAT THING IS WRONG ")
print("AND BIG BRAINS")
print("Test Git changes")
